version: '3.8'

services:
  backend:
    build: ./backend
    image: backend
    volumes:
      - ./backend:/usr/src/app

    ports:
      - 65010:65010


  client:
    build: /client
    image: client
    volumes:
      - ./client:/user/src/app

    ports:
      - 3000:3000



  