version: '3.8'
services:

  nginx:
    image: nginx
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    mem_limit: 300m
      #localhost 80 to continer 80


  backend:
    build: ./backend
    image: backend
    volumes:
      - ./backend:/usr/src/app

    ports:
      - 65010:65010
    container_name: backend

    mem_limit: 300m
    env_file:
      - ./backend/.env


  client:
    build: /client
    image: client
    volumes:
      - ./client:/user/src/app
      # - /app/node_modules

    # ports:
    #   - 3000:3000
    container_name: client

    mem_limit: 300m
    



  